### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by crackfoo** [SINOVATEblockchain/sinovate#1322]
getblocktemplate '{"rules": ["segwit"]}'
error code: -7
error message:
Out of memory

SIN Core RPC client version v24.1.1
Copyright (C) 2009-2022 The Sinovate developers
Copyright (C) 2009-2022 The Bitcoin Core developers

**Comment by furcalor** [comment]
Additionally, when calling getblocktemplate, the error in debug is:
`2023-02-28T13:25:56Z ERROR: TestBlockValidity: Consensus::ContextualCheckBlock: unexpected-witness, ContextualCheckBlock : unexpected witness data found`

**Comment by giaki3003** [comment]
Fixed by aa8745959f21ebd8a4bc1e99dc1eaed04cf49f60
